### ISSUE TITLE
How to use aggregateWithOptions query

### ISSUE THREAD

**Issue by sheldon-markk** [vert-x3/vertx-mongo-client#195]
We are exploring the aggregateWithOptions query using the vertx mongo client and are facing the following error

```
com.mongodb.MongoQueryException: Query failed with error code 2 and error message 'cannot set maxTimeMS on getMore command for a non-awaitData cursor' on server localhost:27017
```

Sample query

```
AggregateOptions aggregateOptions = new AggregateOptions();
        aggregateOptions
               .setAllowDiskUse(true);
        ArrayList<FeedItemData> feedItemDataList = new ArrayList<>();
        mongoClient.aggregateWithOptions(Collections.COLLECTION_FEED_ITEMS,pipeline,aggregateOptions)
.exceptionHandler(throwable -> {
                    future.fail(throwable);
                })
                .endHandler(v -> {
                    future.complete(feedItemDataList);
                   
                })
                .handler(doc -> {
      });
```

**Comment by sheldon-markk** [comment]
Is this only compatible with Mongo 3.6? as we currently use mongo 3.4

**Comment by kostya05983** [comment]
Hello, @sheldon-markk It is a problem of mongo driver, and yes it was fixed in 3.8.0 version. More information you can find here [https://jira.mongodb.org/browse/JAVA-2827](url)

**Comment by sheldon-markk** [comment]
Hi @kostya05983 i check the driver version used in Vert.x 3.7.1 its 3.10.1, but i still get the same error for aggregate. I upgraded mongo to 4.0 and still the same issue.

Is there any config param i need to set in the AggregateOptions?

**Comment by varuas** [comment]
I'm also facing the same issue, using the same versions as @sheldon-markk

**Comment by sheldon-markk** [comment]
For now i have used the following technique and have also tested the same on 3.4, 3.6, 4.0 and 4.2

```
      JsonObject query = new JsonObject();
        query.put(Constants.AGGREGATE, collection);
        query.put(Constants.CURSOR, new JsonObject().put(Constants.BATCH_SIZE,100));
        query.put(Constants.PIPELINE, pipeline);
        mongoClient.runCommand(Constants.AGGREGATE, query, res -> {
            if(res.succeeded()) {
               //success
            }else {
               //failure case
            }
        });
```

**Comment by varuas** [comment]
Thanks a ton @sheldon-markk

**Comment by varuas** [comment]
A drawback of this approach seems to be that we need to manually execute the getmore commands (by providing a cursor ID) if the number of records exceeds the provided batch size (100 in the above example).

**Comment by kostya05983** [comment]
@varuas, I try to see what happens in this week.

**Comment by varuas** [comment]
Thanks @kostya05983 . And to clarify the issue further, the error can be reproduced if we execute any of the two aggregate methods: 
- mongoClient.aggregateWithOptions()
- mongoClient.aggregate()

Provided that the number of results returned by the aggregate query is greater than the batch size (default 20).

The JIRA issue that you linked (JAVA-2827) is only a fix for the JUnit test case. The issue doesn't occur with their driver, it only occurs when using the vertx mongo-client (tried all driver versions from 3.1 to latest 3.11).

**Comment by varuas** [comment]
Hi @kostya05983 , do you have any update on this issue?

At the moment, we are unable to use this library for any kind of aggregations, since anything with a result >= batch size (default batch size is 20) is resulting in the error.

**Comment by kostya05983** [comment]
Hello @varuas , I add a test with aggregateWithOptions, you can see in pull request. All works. [request](https://github.com/vert-x3/vertx-mongo-client/pull/203). You can provide your example and we try to solve an issue.

**Comment by varuas** [comment]
Hi @kostya05983 

Here's a sample unit test taken from your pull request, that will fail:
```
  @Test
  public void testAggregateWithOptions() throws Exception {
    AggregateOptions aggregateOptions = new AggregateOptions();
    aggregateOptions.setAllowDiskUse(true);

    JsonArray pipeline = new JsonArray();
    pipeline.add(new JsonObject().put("$addFields", new JsonObject().put("field", "test")));
    int numDocs = 20;
    final CountDownLatch latch = new CountDownLatch(1);
    final String collection = randomCollection();

    insertDocs(mongoClient, collection, numDocs, onSuccess(res -> {
      mongoClient.aggregateWithOptions(collection, pipeline, aggregateOptions).exceptionHandler(e -> {
        e.printStackTrace();
      }).handler(item -> {
        System.out.println(item.encodePrettily());
      }).fetch(20).endHandler(v -> latch.countDown());
    }));

    awaitLatch(latch);
  }
```

The key difference is that, the value of 'numDocs' has to be set >= 20 to reproduce this error.

**Comment by kostya05983** [comment]
@varuas if you set numDocs more than 20, test will fail 'cause you don't change fetch() to suitable the full amount of documents in collection.

**Comment by varuas** [comment]
@kostya05983 In the above example, I changed the fetch() also. Both numDocs and fetch is set to 20 in the example I shared above. Please check and confirm.

Can you please try to run a test with 20 or more documents? (20 is the batch size, set by default in mongo). I'm pretty confident it will fail. Secondly, I logged the error inside exceptionHandler() in the above example, the error clearly indicates that its an issue.

**Comment by kostya05983** [comment]
Thanks @varuas for case I catched an error, I will try to solve problem.

**Comment by varuas** [comment]
Thanks @kostya05983 . Appreciate your help in this regard.

If there is anyone else reading this, and you're using aggregate() like us, you can set a very high value for batch size in the options as a temporary workaround. In our organization, all aggregation queries have been affected due to this bug, so we are forced to do this workaround (at the cost of performance, of course).

**Comment by kristian** [comment]
Can this issue be reopened? The original suggested fix using Mongo Driver 3.8 did not work as expected. We are also still facing this error when doing aggregations resulting in a very small result set. Thanks!

**Comment by kostya05983** [comment]
Also, There is a PR to fix this, but it is without tests https://github.com/vert-x3/vertx-mongo-client/pull/206

**Comment by kristian** [comment]
Hey @kostya05983, mhm, looking at PR #206, I am unsure whether it‘ll fix this issue. We can reproduce this behaviour even without using any options, e.g. our aggregation pipeline just returns one element (for instance by doing a $count as a last pipeline step).

**Comment by kostya05983** [comment]
Thanks, @kristian can you provide an example for this? How you use it that it returns one element.

**Comment by varuas** [comment]
+1 to what @kristian said. As mentioned previously in this thread, this error occurs even for the basic aggregate() method (in addition to the aggregateWithOptions() method). It doesn't matter what the end pipeline returns, as long as the result size is greater than default batch size.

> Thanks @kostya05983 . And to clarify the issue further, the error can be reproduced if we execute any of the two aggregate methods:
> 
> * mongoClient.aggregateWithOptions()
> * mongoClient.aggregate()
> 
> Provided that the number of results returned by the aggregate query is greater than the batch size (default 20).

**Comment by kristian** [comment]
@kostya05983, the following aggregation causes an issue with the same error message on our end, regardless of the collection we run it on:

`mongoClient.aggregate(COLLECTION, new JsonArray().add(new JsonObject().put("$count", "count")))`

This is a slight simplification, we are doing a $group beforehand, which is why we cannot use the native .count method of MongoDB.

**Comment by sheldon-markk** [comment]
> A drawback of this approach seems to be that we need to manually execute the getmore commands (by providing a cursor ID) if the number of records exceeds the provided batch size (100 in the above example).

Yes we have started facing this issue, so whats the solution here?

**Comment by vietj** [comment]
can one clarify or determine whether it is an issue in this client or in the wrapped Mongo client ?

**Comment by varuas** [comment]
> can one clarify or determine whether it is an issue in this client or in the wrapped Mongo client ?

@vietj This is an issue with this client library (the original Mongo client works perfectly for aggregations). Basically *any* kind of aggregation cannot be used with this library (doesn't matter what the actual query is) since it doesn't seem to have the logic to fetch more results when size >= 20 and even worse, it results in an error.

**Comment by kostya05983** [comment]
@varuas, @vietj  We use asyncBatchCursor, that's why we can't set maxAwaitTimeMs property. I delete this possibility for now. Maybe we should implement it on our layer in future.
